# Generated by Django 4.1.7 on 2023-04-24 14:44

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginsystem', '0004_userarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarticle',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userarticle',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='userarticle',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userarticle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
