# Generated by Django 4.1.7 on 2023-04-24 15:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsystem', '0006_article_delete_userarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='indeximg',
            field=models.ImageField(default='images/home9.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
