# Generated by Django 4.1.7 on 2023-04-27 15:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginsystem', '0010_remove_profile_created_alter_article_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='ArticleUser',
        ),
    ]
