# Generated by Django 4.1.7 on 2023-05-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsystem', '0011_rename_article_articleuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleUser',
        ),
    ]
