# Generated by Django 4.1.7 on 2023-05-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsystem', '0016_alter_articleuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleuser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
