# Generated by Django 4.1.7 on 2023-04-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('details', models.CharField(blank=True, max_length=100000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
